### ISSUE TITLE
Make SpotScore API specification / pro forma documentation using Swagger

### ISSUE THREAD

**Issue by bolot1989** [SpotScore/spotscore.github.io#8]
Needed SpotScore API capabilities:
1. GET /objects/?location={X,Y}&?address={user input}&?categories={A, B, C, ...}&?bbox={x1,y1,x2,y2}&?radius={some amount of meters}

Limitations:
1. Number of objects to be returned
2. Number of meters of radius or diameter of bbox

Returns: JSON objects array (see later definition)
1. GET /categories/?query={user input}

Returns: JSON array of categories
1. GET /object/{object_id}

Returns:  JSON object of information
1. GET /nearest/?location={X,Y}&?address={user input}&?categories={A, B, C, ...}&?bbox={x1,y1,x2,y2}&?radius={some amount of meters} -> JSON object array

Returns: JSON objects array (see later definition)

**Comment by rando345** [comment]
commit: 828019c7b21b2b52e22d1433339833f668785fba in https://github.com/SpotScore/spotscore-swagger-docs
